using System.Net.Http.Json;
using GiftOfTheGivers.Web.Data;
using GiftOfTheGivers.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace GiftOfTheGivers.Web.Controllers;

public class DonateController : Controller
{
    private readonly ApplicationDbContext _db;
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly IConfiguration _configuration;

    public DonateController(
        ApplicationDbContext db,
        IHttpClientFactory httpClientFactory,
        IConfiguration configuration)
    {
        _db = db;
        _httpClientFactory = httpClientFactory;
        _configuration = configuration;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View(new Donation());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(Donation donation)
    {
        if (!ModelState.IsValid)
            return View(donation);

        donation.DonationDate = DateTime.UtcNow;

        donation.DonorName = donation.IsAnonymous
            ? "Anonymous Donor"
            : (User.Identity?.Name ?? "Guest Donor");

        // Get the Azure Function URL from appsettings.json
        var functionUrl = _configuration["AzureFunction:DonationUrl"];

        if (string.IsNullOrWhiteSpace(functionUrl))
        {
            ModelState.AddModelError(
                "",
                "The Azure Donation Function URL has not been configured.");

            return View(donation);
        }

        // Create the HTTP client
        var client = _httpClientFactory.CreateClient();

        // Send the donation information to the Azure Function
        var functionRequest = new
        {
            amount = donation.Amount,
            donationType = donation.DonationType,
            currency = donation.Currency,
            isAnonymous = donation.IsAnonymous
        };

        try
        {
            var functionResponse =
                await client.PostAsJsonAsync(functionUrl, functionRequest);

            if (!functionResponse.IsSuccessStatusCode)
            {
                var errorBody = await functionResponse.Content.ReadAsStringAsync();

                ModelState.AddModelError(
                    "",
                    $"Azure Function Error: {(int)functionResponse.StatusCode} " +
                    $"{functionResponse.StatusCode}. " +
                    $"Response: {errorBody}");

                return View(donation);
            }

            // Read the certificate returned by the Function
            var functionResult =
                await functionResponse.Content.ReadFromJsonAsync<DonationFunctionResponse>();

            if (functionResult == null ||
                string.IsNullOrWhiteSpace(functionResult.CertificateNumber))
            {
                ModelState.AddModelError(
                    "",
                    "The Azure Function did not return a certificate number.");

                return View(donation);
            }

            // Use the certificate number generated by the Azure Function
            donation.TaxCertificateNumber =
                functionResult.CertificateNumber;

            // Save the donation
            _db.Donations.Add(donation);

            await _db.SaveChangesAsync();

            return RedirectToAction(
                nameof(Certificate),
                new { id = donation.Id });
        }
        catch (Exception ex)
        {
            ModelState.AddModelError(
                "",
                $"Unable to connect to the Azure Donation Function. " +
                $"Error: {ex.Message}");

            return View(donation);
        }
    }

    public async Task<IActionResult> Certificate(int id)
    {
        var donation = await _db.Donations.FindAsync(id);

        return donation is null
            ? NotFound()
            : View(donation);
    }

    private class DonationFunctionResponse
    {
        public string CertificateNumber { get; set; } = "";

        public string Message { get; set; } = "";
    }
}